[package]
name = "libbcm-host-sys"
version = "0.1.0"
authors = ["takayuki <takayuki@idein.jp>"]

[lib]
name = "libbcm_host_sys"
path = "lib.rs"

[build-dependencies]
bindgen = "0.26.3"

[dependencies]

