[package]
name = "bcm-host-sys"
version = "0.1.0"
authors = ["takayuki <takayuki@idein.jp>"]

[lib]
name = "bcm_host_sys"
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.32.1"

[dependencies]

